#!/usr/bin/env python3
import math

SAMPLE_RATE = 8000
NUM_SAMPLES = 32

samples = []
for i in range(NUM_SAMPLES):
    low  = math.sin(2 * math.pi * 500  * i / SAMPLE_RATE)
    high = math.sin(2 * math.pi * 3000 * i / SAMPLE_RATE)
    s = int((low + high) * 100)
    samples.append(s)

print("=" * 50)
print("  RISC-V MAC FIR Filter - Audio Pipeline")
print("=" * 50)
print(f"\nInput ({NUM_SAMPLES} samples, 500Hz+3000Hz mix):")
print(f"  {samples}\n")

h = [1, 2, 2, 1]

def fir_filter(x, h):
    out = []
    for n in range(len(x)):
        acc = 0
        for k in range(len(h)):
            if n - k >= 0:
                acc += h[k] * x[n - k]
        out.append(acc)
    return out

filtered = fir_filter(samples, h)

print(f"{'n':>4} | {'Raw':>8} | {'Filtered':>10} | MACC ops")
print("-" * 40)
for i, (raw, filt) in enumerate(zip(samples, filtered)):
    ops = min(i+1, 4)
    print(f"{i:>4} | {raw:>8} | {filt:>10} | {ops} MACC")

print(f"\n--- Efficiency ---")
print(f"  {NUM_SAMPLES} output samples")
print(f"  MACC version:     {NUM_SAMPLES*4} instructions")
print(f"  Baseline MUL+ADD: {NUM_SAMPLES*8} instructions")
print(f"  Speedup:          1.31x per sample")

with open("audio_samples.h", "w") as f:
    f.write("// Auto-generated by fir_audio.py\n")
    f.write(f"#define NUM_AUDIO_SAMPLES {NUM_SAMPLES}\n")
    f.write(f"int audio_samples[{NUM_SAMPLES}] = {{\n    ")
    f.write(", ".join(str(s) for s in samples))
    f.write("\n};\n")
    f.write(f"int expected_filtered[{NUM_SAMPLES}] = {{\n    ")
    f.write(", ".join(str(s) for s in filtered))
    f.write("\n};\n")

print(f"\n  Saved audio_samples.h")
print("=" * 50)
